name: pinact

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/pinact.yaml"
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - ".github/pinact.yaml"

permissions:
  contents: read

jobs:
  pinact:
    name: Verify actions are pinned
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: suzuki-shunsuke/pinact-action@896d595f299e71d65b9d28349d6956abe144390a # v3.0.0
        with:
          fix: "false"
          github_token: ${{ github.token }}
          config: .github/pinact.yaml
